# `Hello World`を返す意思疎通用のAPI。
GET http://localhost:8000

###

# サインアップAPI。
POST http://localhost:8000/sign_up
Content-Type: application/json

{
  "name": "your-name",
  "email": "user@example.com",
  "password": "Password1234"
}

###

# 認証コードを検証するAPI。
POST http://localhost:8000/verify_code
Content-Type: application/json

{
  "email": "user@example.com",
  "code": "123456"
}

###

# 認証コードを再送するAPI。
POST http://localhost:8000/resend_code
Content-Type: application/json

{
  "email": "user@example.com"
}

###

# サインインするAPI。
POST http://localhost:8000/sign_in
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password1234"
}
